---
name: Inadyn
version: dev
slug: inadyn
description: Inadyn is a small and simple Dynamic DNS, DDNS, client with HTTPS support
url: https://github.com/lbouriez/addon-inadyn
image: ghcr.io/lbouriez/addon-inadyn/{arch}
arch:
  - aarch64
  - amd64
  - armv7
map:
  - ssl
options:
  providers:
    - provider: yourprovider
      username: username
      password: password
      hostname: dynamic-subdomain.example.com
schema:
  verify_address: bool?
  fake_address: bool?
  allow_ipv6: bool?
  iface: str?
  iterations: int?
  period: int?
  forced_update: int?
  secure_ssl: bool?
  providers:
    - provider": str
      custom_provider": bool?
      username": str
      password": str?
      ssl": bool?
      hostname": str
      checkip_ssl": bool?
      checkip_server": str?
      checkip_command": str?
      checkip_path": str?
      user_agent": str?
      wildcard": bool?
      ddns_server": str?
      ddns_path": str?
      append_myip": bool?
      proxied": bool?
      ttl": int?
